### ISSUE TITLE
data augmentation

### ISSUE THREAD

**Issue by IzzaRabbani** [yassouali/pytorch-segmentation#116]
Want to do all these data augmentation on custom dataset, what shoul I do?
- cropped sub images or splits
- Brightness modulation
- Contrast modulation
- random crop
- Zoomed
- Flip
- rotation

**Comment by yassouali** [comment]
You can check this [method](https://github.com/yassouali/pytorch-segmentation/blob/af0107949d79154f24512d326e9dfde29b71f4cf/base/base_dataset.py#L63) for the available augmentations. I think you'll need to add the photometric augmentations since they are not implemented, but I don't think it'll be quite straightforward.
